Document: terepaima
Title: Debian terepaima Manual
Author: <insert document author here>
Abstract: This manual describes what terepaima is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/terepaima/terepaima.sgml.gz

Format: postscript
Files: /usr/share/doc/terepaima/terepaima.ps.gz

Format: text
Files: /usr/share/doc/terepaima/terepaima.text.gz

Format: HTML
Index: /usr/share/doc/terepaima/html/index.html
Files: /usr/share/doc/terepaima/html/*.html
